In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
gdp_df = pd.read_csv("../data/gdp_percapita.csv", nrows=6869)
gdp_df.head()

Country or Area  Year        Value  Value Footnotes
0     Afghanistan  2019  2065.036398              NaN
1     Afghanistan  2018  2033.779002              NaN
2     Afghanistan  2017  2058.383832              NaN
3     Afghanistan  2016  2057.062164              NaN
4     Afghanistan  2015  2068.265904              NaN

In [2]:
internet_df = pd.read_csv('../data/internet_use.csv',nrows=4496)
internet_df.head()

Country or Area  Year     Value  Value Footnotes
0     Afghanistan  2014  6.390000              NaN
1     Afghanistan  2013  5.900000              NaN
2     Afghanistan  2012  5.454545              NaN
3     Afghanistan  2011  5.000000              NaN
4     Afghanistan  2010  4.000000              NaN

7. Look at the shape of each DataFrame - how many rows? How many columns?

In [3]:
print(gdp_df.shape)

(6869, 4)


gdp_df has 6869 rows and 4 columns

In [4]:
print(internet_df.shape)

(4496, 4)


internet_df has 4496 rows and 4 columns

8. Take a look at the datatypes for the columns in each DataFrame.

In [5]:
print(gdp_df.dtypes)

Country or Area     object
Year                object
Value              float64
Value Footnotes    float64
dtype: object


In [6]:
print(internet_df.dtypes)

Country or Area     object
Year                object
Value              float64
Value Footnotes    float64
dtype: object


9. Take a look at the last 10 rows of each DataFrame in turn.

In [7]:
print(gdp_df.iloc[-10:])

     Country or Area      Year        Value  Value Footnotes
6859        Zimbabwe      1998  3653.920016              NaN
6860        Zimbabwe      1997  3580.048793              NaN
6861        Zimbabwe      1996  3520.430146              NaN
6862        Zimbabwe      1995  3226.413930              NaN
6863        Zimbabwe      1994  3263.934978              NaN
6864        Zimbabwe      1993  3033.504852              NaN
6865        Zimbabwe      1992  3054.889178              NaN
6866        Zimbabwe      1991  3426.598094              NaN
6867        Zimbabwe      1990  3324.348171              NaN
6868   footnoteSeqID  Footnote          NaN              NaN


In [8]:
print(internet_df.iloc[-10:])

     Country or Area      Year     Value  Value Footnotes
4486        Zimbabwe      2001  0.799846              NaN
4487        Zimbabwe      2000  0.401434              NaN
4488        Zimbabwe      1999  0.161676              NaN
4489        Zimbabwe      1998  0.081648              NaN
4490        Zimbabwe      1997  0.033080              NaN
4491        Zimbabwe      1996  0.016790              NaN
4492        Zimbabwe      1995  0.007684              NaN
4493        Zimbabwe      1994  0.001739              NaN
4494        Zimbabwe      1990  0.000000              NaN
4495   footnoteSeqID  Footnote       NaN              NaN


10. Drop the value footnotes column from both DataFrames. Check that this worked as expected.

In [9]:
gdp_df = gdp_df.drop(['Value Footnotes'], axis = 1)
internet_df = internet_df.drop(['Value Footnotes'], axis = 1)
print(gdp_df)
print(internet_df)

     Country or Area      Year        Value
0        Afghanistan      2019  2065.036398
1        Afghanistan      2018  2033.779002
2        Afghanistan      2017  2058.383832
3        Afghanistan      2016  2057.062164
4        Afghanistan      2015  2068.265904
...              ...       ...          ...
6864        Zimbabwe      1993  3033.504852
6865        Zimbabwe      1992  3054.889178
6866        Zimbabwe      1991  3426.598094
6867        Zimbabwe      1990  3324.348171
6868   footnoteSeqID  Footnote          NaN

[6869 rows x 3 columns]
     Country or Area      Year     Value
0        Afghanistan      2014  6.390000
1        Afghanistan      2013  5.900000
2        Afghanistan      2012  5.454545
3        Afghanistan      2011  5.000000
4        Afghanistan      2010  4.000000
...              ...       ...       ...
4491        Zimbabwe      1996  0.016790
4492        Zimbabwe      1995  0.007684
4493        Zimbabwe      1994  0.001739
4494        Zimbabwe      1990  0.000

11. Change the columns for the GDP Per Capita DataFrame to ‘Country’, ‘Year’, and ‘GDP_Per_Capita’.

In [10]:
gdp_df = gdp_df.rename(columns={"Country or Area":"Country", 'Value':'GDP_Per_Capita'})
print(gdp_df)

            Country      Year  GDP_Per_Capita
0       Afghanistan      2019     2065.036398
1       Afghanistan      2018     2033.779002
2       Afghanistan      2017     2058.383832
3       Afghanistan      2016     2057.062164
4       Afghanistan      2015     2068.265904
...             ...       ...             ...
6864       Zimbabwe      1993     3033.504852
6865       Zimbabwe      1992     3054.889178
6866       Zimbabwe      1991     3426.598094
6867       Zimbabwe      1990     3324.348171
6868  footnoteSeqID  Footnote             NaN

[6869 rows x 3 columns]


12. Change the columns for the Internet Users DataFrame to ‘Country’, ‘Year’, and ‘Internet_Users_Pct’.

In [11]:
internet_df = internet_df.rename(columns={"Country or Area": "Country", 'Value':'Internet_Users_Pct'})
print(internet_df)

            Country      Year  Internet_Users_Pct
0       Afghanistan      2014            6.390000
1       Afghanistan      2013            5.900000
2       Afghanistan      2012            5.454545
3       Afghanistan      2011            5.000000
4       Afghanistan      2010            4.000000
...             ...       ...                 ...
4491       Zimbabwe      1996            0.016790
4492       Zimbabwe      1995            0.007684
4493       Zimbabwe      1994            0.001739
4494       Zimbabwe      1990            0.000000
4495  footnoteSeqID  Footnote                 NaN

[4496 rows x 3 columns]


13. Merge the two DataFrames to one. Merge all rows from each of the two DataFrames. Call the new DataFrame gdp_and_internet_use.

In [12]:
gdp_and_internet_use = pd.concat([gdp_df, internet_df])
ignore_index=True
print(gdp_and_internet_use)

            Country      Year  GDP_Per_Capita  Internet_Users_Pct
0       Afghanistan      2019     2065.036398                 NaN
1       Afghanistan      2018     2033.779002                 NaN
2       Afghanistan      2017     2058.383832                 NaN
3       Afghanistan      2016     2057.062164                 NaN
4       Afghanistan      2015     2068.265904                 NaN
...             ...       ...             ...                 ...
4491       Zimbabwe      1996             NaN            0.016790
4492       Zimbabwe      1995             NaN            0.007684
4493       Zimbabwe      1994             NaN            0.001739
4494       Zimbabwe      1990             NaN            0.000000
4495  footnoteSeqID  Footnote             NaN                 NaN

[11365 rows x 4 columns]


14. Look at the first five rows of your new DataFrame to confirm it merged correctly.

In [13]:
print(gdp_and_internet_use.head())

       Country  Year  GDP_Per_Capita  Internet_Users_Pct
0  Afghanistan  2019     2065.036398                 NaN
1  Afghanistan  2018     2033.779002                 NaN
2  Afghanistan  2017     2058.383832                 NaN
3  Afghanistan  2016     2057.062164                 NaN
4  Afghanistan  2015     2068.265904                 NaN


15. Look at the last five rows to make sure the data is clean and as expected.

In [14]:
print(gdp_and_internet_use.tail())

            Country      Year  GDP_Per_Capita  Internet_Users_Pct
4491       Zimbabwe      1996             NaN            0.016790
4492       Zimbabwe      1995             NaN            0.007684
4493       Zimbabwe      1994             NaN            0.001739
4494       Zimbabwe      1990             NaN            0.000000
4495  footnoteSeqID  Footnote             NaN                 NaN


16. Subset the combined DataFrame to keep only the data for 2004, 2009, and 2014. Check that this happened correctly.

In [15]:
array = ['2004', '2009', '2014']
print(gdp_and_internet_use.loc[gdp_and_internet_use['Year'].isin(array)])

          Country  Year  GDP_Per_Capita  Internet_Users_Pct
5     Afghanistan  2014     2102.385234                 NaN
10    Afghanistan  2009     1758.904043                 NaN
15    Afghanistan  2004     1200.278256                 NaN
23        Albania  2014    11623.866679                 NaN
28        Albania  2009    10346.864199                 NaN
...           ...   ...             ...                 ...
4456       Zambia  2009             NaN            6.310000
4461       Zambia  2004             NaN            2.013550
4473     Zimbabwe  2014             NaN           19.890000
4478     Zimbabwe  2009             NaN           11.360000
4483     Zimbabwe  2004             NaN            6.564045

[1312 rows x 4 columns]


17. Create three new DataFrames, one for 2004, one for 2009, and one for 2014. Give them meaningful names that aren't too long.

In [16]:
four = gdp_and_internet_use.loc[gdp_and_internet_use['Year'] == '2004']
nine = gdp_and_internet_use.loc[gdp_and_internet_use['Year'] == '2009']
fourteen = gdp_and_internet_use.loc[gdp_and_internet_use['Year'] == '2014']

print(four.head())
print(nine.head())
print(fourteen.head())

                 Country  Year  GDP_Per_Capita  Internet_Users_Pct
15           Afghanistan  2004     1200.278256                 NaN
33               Albania  2004     7604.838002                 NaN
63               Algeria  2004    10058.435939                 NaN
93                Angola  2004     5593.241537                 NaN
123  Antigua and Barbuda  2004    18745.681534                 NaN
                 Country  Year  GDP_Per_Capita  Internet_Users_Pct
10           Afghanistan  2009     1758.904043                 NaN
28               Albania  2009    10346.864199                 NaN
58               Algeria  2009    10782.361398                 NaN
88                Angola  2009     7643.493749                 NaN
118  Antigua and Barbuda  2009    20046.839017                 NaN
                 Country  Year  GDP_Per_Capita  Internet_Users_Pct
5            Afghanistan  2014     2102.385234                 NaN
23               Albania  2014    11623.866679                

18. Which country had the highest percentage of internet users in 2014? What was the percentage? (Try typing the first 3 letters of your DataFrame name and hitting the tab key for auto-complete options).